models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo
    api_key: "${OPENAI_API_KEY}"  # Ensure your env variables are correctly set
    temperature: 0.7
    max_tokens: 300

guardrails:
  colang_path: "nemo_guardrails/colang_rules.co"
  llm_model: "gpt-3.5-turbo"
  rail_type: "response"

